# Generated by Django 4.0 on 2022-02-06 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyumsa1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfEntry', models.IntegerField(choices=[(1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('course', models.CharField(max_length=120)),
                ('homeAddress', models.CharField(max_length=150)),
                ('nextOfKin', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('brother', 'brother'), ('Sister', 'Sister'), ('Wife', 'Wife'), ('Husband', 'Husband'), ('Other', 'Other')], max_length=150)),
                ('contactNOK', models.CharField(blank=True, max_length=15)),
                ('maritialStatus', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=20)),
                ('DoB', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('faculty', models.CharField(max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('hall', models.CharField(choices=[('Kulubya', 'Kulubya'), ('Nanziri', 'Nanziri'), ('Mandella', 'Mandella'), ('Pearl', 'Pearl'), ('North Hall', 'North Hall')], max_length=233)),
                ('residenceStatus', models.CharField(choices=[('Resident', 'Resident'), ('Non-Resident', 'Non-Resident')], max_length=50)),
                ('recentSch', models.CharField(blank=True, max_length=255, null=True)),
                ('award', models.CharField(blank=True, max_length=55, null=True)),
                ('respnosibilityHeld', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyumsa1.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alumin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearOfEntry', models.IntegerField(choices=[(1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('course', models.CharField(max_length=120)),
                ('homeAddress', models.CharField(max_length=150)),
                ('nextOfKin', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('brother', 'brother'), ('Sister', 'Sister'), ('Wife', 'Wife'), ('Husband', 'Husband'), ('Other', 'Other')], max_length=150)),
                ('contactNOK', models.CharField(blank=True, max_length=15)),
                ('maritialStatus', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=20)),
                ('DoB', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('yrOfCompletion', models.IntegerField(choices=[(1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='year')),
                ('positionHeldAtKyumsa', models.CharField(max_length=100, verbose_name='KYUMSA POSITION')),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('jobDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('since', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyumsa1.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
